# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondetails',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='depomaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='divisionmaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='tariffheader',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='tariffmaster',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True),
        ),
    ]
