# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_auto_20180328_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='customer_pincode',
            field=models.CharField(blank=True, db_column='CUSTPIN', max_length=10, null=True),
        ),
    ]
