# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-28 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_auto_20191007_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmaster',
            name='all_quantity',
            field=models.FloatField(db_column='ALLQTY'),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='clear_stock',
            field=models.FloatField(db_column='CLSTK'),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='op_number',
            field=models.FloatField(db_column='OPNO'),
        ),
        migrations.AlterField(
            model_name='stockmaster',
            name='op_stock',
            field=models.FloatField(db_column='OPSTK'),
        ),
    ]
