# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-30 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connector', '0003_auto_20200128_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdjustmentDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column=b'DJCREATEDDATE')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True)),
                ('is_sync', models.BooleanField(db_column=b'ISSYNC', default=False)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_column='INVNO', default=0, max_length=15)),
                ('invoice_date', models.DateField(blank=True, db_column='INVDT', null=True)),
                ('adjusted_amount', models.FloatField(blank=True, db_column='ADJAMT', null=True)),
                ('customer_code', models.IntegerField(blank=True, db_column='CUSTCODE', null=True)),
                ('is_adjusted', models.CharField(blank=True, db_column='ADJUST', max_length=1, null=True)),
                ('adjust_type', models.CharField(blank=True, db_column='ADJTYPE', max_length=4, null=True)),
                ('doc_number', models.IntegerField(blank=True, db_column='DOCNUM', null=True)),
                ('doc_date', models.DateField(blank=True, db_column='DOCDT', null=True)),
                ('doc_amount', models.FloatField(blank=True, db_column='DOCAMT', null=True)),
                ('alloc_number', models.IntegerField(blank=True, db_column='ALLOCNO', default=0)),
                ('alloc_date', models.DateField(blank=True, db_column='ALLOCDT', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column=b'DJCREATEDBY', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_paymentadjustmentdetails_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column=b'DJMODIFIEDBY', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_paymentadjustmentdetails_set', to=settings.AUTH_USER_MODEL)),
                ('recept_id', models.ForeignKey(blank=True, db_column='COLHDRID', null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.CollectionHeader')),
            ],
            options={
                'db_table': 'GCP_ST21_ALL_ADJ',
                'verbose_name_plural': 'Payment Adjustments',
            },
        ),
    ]
