# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_auto_20180329_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='order',
            field=models.ForeignKey(db_column='ORDID', default=1, on_delete=django.db.models.deletion.CASCADE, to='connector.OrderHeader'),
            preserve_default=False,
        ),
    ]
