# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_invoicedetails_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderheader',
            unique_together=set([('order_number', 'sfa_order_number', 'order_date')]),
        ),
    ]
