# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_auto_20180418_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together=set([('order', 'product_code')]),
        ),
    ]
