# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-15 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_paymentadjustmentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='close_flag',
            field=models.IntegerField(blank=True, db_column='CFLAG', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentadjustmentdetails',
            name='alloc_number',
            field=models.IntegerField(blank=True, db_column='ALLOCNO', default=0, null=True),
        ),
    ]
