# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-23 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_nationalpaymentpendingview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalpaymentpendingview',
            options={'managed': False, 'verbose_name_plural': 'National Payment View'},
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='bouns_flag',
            field=models.IntegerField(blank=True, db_column='BOUNSFLAG', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='close_flag',
            field=models.IntegerField(blank=True, db_column='CLOSEFLAG', default=0),
        ),
    ]
