# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_auto_20180418_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_number',
            field=models.CharField(db_column='INVNO', max_length=15),
        ),
    ]
