# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_auto_20210115_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentadjustmentdetails',
            name='doc_number',
            field=models.ForeignKey(blank=True, db_column='DOCNUM', null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.CollectionHeader'),
        ),
    ]
