# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_auto_20180418_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondetails',
            name='cgst_amount',
            field=models.FloatField(blank=True, db_column='CGSTAMT', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='cgst_per',
            field=models.FloatField(blank=True, db_column='CGSTPER', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='igst_amount',
            field=models.FloatField(blank=True, db_column='IGST', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='igst_per',
            field=models.FloatField(blank=True, db_column='IGSTPER', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='othamt',
            field=models.FloatField(blank=True, db_column='OTHAMT', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='received_amount',
            field=models.FloatField(blank=True, db_column='RECDAMT', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='sgst_amount',
            field=models.FloatField(blank=True, db_column='SGSTAMT', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='sgst_per',
            field=models.FloatField(blank=True, db_column='SGSTPER', null=True),
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='total_tax_value',
            field=models.FloatField(blank=True, db_column='TAXABLE_VALUE', null=True),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='advance_amount',
            field=models.FloatField(blank=True, db_column='ADVAMT', null=True),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='courier_charges',
            field=models.FloatField(blank=True, db_column='COUR_CHARG', null=True),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='received_amount',
            field=models.FloatField(db_column='RECDAMT'),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='round_minus',
            field=models.FloatField(blank=True, db_column='ROUNDMINUS', null=True),
        ),
        migrations.AlterField(
            model_name='collectionheader',
            name='round_plus',
            field=models.FloatField(blank=True, db_column='ROUNDPLUS', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='amount',
            field=models.FloatField(db_column='AMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='cgst_amount',
            field=models.FloatField(db_column='CGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='cgst_per',
            field=models.FloatField(db_column='CGSTPER'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='discount_amount',
            field=models.FloatField(db_column='DISCAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='discount_percentage',
            field=models.FloatField(db_column='DISCPERC'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='igst_amount',
            field=models.FloatField(db_column='IGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='igst_per',
            field=models.FloatField(db_column='IGSTPER'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='net_amount',
            field=models.FloatField(db_column='NETAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='product_rate',
            field=models.FloatField(db_column='PRODRATE'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='sgst_amount',
            field=models.FloatField(db_column='SGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='sgst_per',
            field=models.FloatField(db_column='SGSTPER'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_amount',
            field=models.FloatField(db_column='TAXAMT'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total',
            field=models.FloatField(db_column='TOT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='advance_amount',
            field=models.FloatField(db_column='ADVAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='balance_amount',
            field=models.FloatField(db_column='BALAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='credit_amount',
            field=models.FloatField(db_column='CRAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='dr_amount',
            field=models.FloatField(db_column='DRAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_amount',
            field=models.FloatField(db_column='INVAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='net_amount',
            field=models.FloatField(db_column='NETAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='other_charges',
            field=models.FloatField(db_column='OTHER_CHGS'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='paid_amount',
            field=models.FloatField(db_column='PAIDAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='roundoff',
            field=models.FloatField(db_column='ROUNDEDOFF'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total',
            field=models.FloatField(db_column='TOT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_cgst_amount',
            field=models.FloatField(db_column='TOT_CGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_discount',
            field=models.FloatField(db_column='TOT_DISC'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_discount_value',
            field=models.FloatField(db_column='TOT_DISCOUNT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_igst_amount',
            field=models.FloatField(db_column='TOT_IGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_product_value',
            field=models.FloatField(db_column='TOT_PRODVAL'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_sgst_amount',
            field=models.FloatField(db_column='TOT_SGSTAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax_amount',
            field=models.FloatField(db_column='TOT_TAXAMT'),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_tax_value',
            field=models.FloatField(db_column='TOT_TAXABLE_VALUE'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='adjust_value',
            field=models.FloatField(blank=True, db_column='ADJVALUE', null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.FloatField(db_column='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='discount',
            field=models.FloatField(blank=True, db_column='DISCOUNT', null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='discount',
            field=models.FloatField(blank=True, db_column='DISCTOT', null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_value',
            field=models.FloatField(db_column='ORDVAL'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_value_rs',
            field=models.FloatField(blank=True, db_column='ORDVALRS', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(db_column='PRICE'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionheader',
            unique_together=set([('depo_code', 'receipt_number', 'sfa_receipt_id')]),
        ),
    ]
