# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_auto_20210226_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='masid',
            field=models.IntegerField(blank=True, db_column='MASID', default=0),
        ),
    ]
