# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_auto_20210226_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='masid',
            field=models.IntegerField(blank=True, db_column='MASID', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='advance_amount',
            field=models.FloatField(db_column='ADVAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='bouns_flag',
            field=models.IntegerField(db_column='BOUNSFLAG', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='close_flag',
            field=models.IntegerField(db_column='CLOSEFLAG', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='credit_amount',
            field=models.FloatField(db_column='CRAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='dr_amount',
            field=models.FloatField(db_column='DRAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='grn_flag',
            field=models.IntegerField(db_column='GRNFLAG', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_amount',
            field=models.FloatField(db_column='INVAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='net_amount',
            field=models.FloatField(db_column='NETAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='other_charges',
            field=models.FloatField(db_column='OTHER_CHGS', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='paid_amount',
            field=models.FloatField(blank=True, db_column='PAIDAMT', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='roundoff',
            field=models.FloatField(db_column='ROUNDEDOFF', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='tot_grnvalue',
            field=models.IntegerField(db_column='TOT_GRNVALUE', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_cgst_amount',
            field=models.FloatField(db_column='TOT_CGSTAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_igst_amount',
            field=models.FloatField(db_column='TOT_IGSTAMT', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_sgst_amount',
            field=models.FloatField(db_column='TOT_SGSTAMT', default=0),
        ),
    ]
