# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20180518_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='count',
            field=models.IntegerField(db_column='PRODCNT', null=True),
        ),
    ]
