# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_auto_20180518_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmaster',
            name='hsn_code',
            field=models.CharField(db_column='HSNCODE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tariffmaster',
            name='tariff_header',
            field=models.ForeignKey(db_column='TARIFFHD', null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.TariffHeader'),
        ),
    ]
