# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_auto_20180518_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffmaster',
            name='tariff_header',
            field=models.CharField(db_column='TARIFFHD', max_length=100, null=True),
        ),
    ]
