# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_auto_20180518_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffheader',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tariffheader',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tariffheader',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='TariffHeader',
        ),
    ]
