# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0013_auto_20180614_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='sub_category_code',
            field=models.IntegerField(blank=True, db_column='SUBGRP', null=True),
        ),
    ]
