# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connector', '0014_productmaster_sub_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepoSalesRep',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column=b'DJCREATEDDATE')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column=b'DJMODIFIEDDATE', null=True)),
                ('is_sync', models.BooleanField(db_column=b'ISSYNC', default=False)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=3)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('mobile', models.CharField(db_column='MOBILE', max_length=15)),
                ('email_id', models.CharField(db_column='MAILID', max_length=35)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column=b'DJCREATEDBY', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_deposalesrep_set', to=settings.AUTH_USER_MODEL)),
                ('depo_code', models.ForeignKey(db_column='DEPOCODE', on_delete=django.db.models.deletion.CASCADE, to='connector.DepoMaster')),
                ('modified_by', models.ForeignKey(blank=True, db_column=b'DJMODIFIEDBY', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_deposalesrep_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GCP_SM05_FLD',
                'verbose_name_plural': 'Depo Sales Representatives',
            },
        ),
        migrations.AlterUniqueTogether(
            name='deposalesrep',
            unique_together=set([('code', 'depo_code')]),
        ),
    ]
