# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0015_auto_20180619_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='market_code',
            field=models.ForeignKey(blank=True, db_column='MKTCODEID', null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.Market'),
        ),
    ]
