# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_auto_20180619_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='actual_market_code',
            field=models.IntegerField(blank=True, db_column='MKTCODE', null=True),
        ),
    ]
