# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0020_auto_20180620_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='bank_code',
            field=models.CharField(blank=True, db_column='BNKCODE', max_length=50, null=True),
        ),
    ]
