# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0021_auto_20180620_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='bank_document_date',
            field=models.DateField(blank=True, db_column='BNKDOCDT', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='gross_weight',
            field=models.IntegerField(blank=True, db_column='GROSSWT', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total',
            field=models.FloatField(blank=True, db_column='TOT', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='total_discount',
            field=models.FloatField(blank=True, db_column='TOT_DISC', null=True),
        ),
    ]
