# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0023_auto_20180620_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheader',
            name='paid_amount',
            field=models.FloatField(blank=True, db_column='PAIDAMT', null=True),
        ),
    ]
