# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0028_auto_20180621_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='discount_amount',
            field=models.FloatField(blank=True, db_column='DISCAMT', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='discount_percentage',
            field=models.FloatField(blank=True, db_column='DISCPERC', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='net_amount',
            field=models.FloatField(blank=True, db_column='NETAMT', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax_amount',
            field=models.FloatField(blank=True, db_column='TAXAMT', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total',
            field=models.FloatField(blank=True, db_column='TOT', null=True),
        ),
    ]
