# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0029_auto_20180621_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='cgst_per',
            field=models.FloatField(blank=True, db_column='CGSTPER', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='igst_per',
            field=models.FloatField(blank=True, db_column='IGSTPER', null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='sgst_per',
            field=models.FloatField(blank=True, db_column='SGSTPER', null=True),
        ),
    ]
