# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0030_auto_20180621_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionheader',
            name='customer_code',
            field=models.ForeignKey(db_column='CUSTCODEID', on_delete=django.db.models.deletion.CASCADE, to='connector.CustomerMaster'),
        ),
    ]
