# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0031_auto_20180621_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionheader',
            name='customer',
            field=models.IntegerField(blank=True, db_column='CUSTCODE', null=True),
        ),
    ]
