# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0032_collectionheader_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiondetails',
            name='order_code',
        ),
        migrations.AlterField(
            model_name='collectiondetails',
            name='collection',
            field=models.ForeignKey(db_column='COLHDRID', on_delete=django.db.models.deletion.CASCADE, to='connector.CollectionHeader'),
        ),
    ]
