# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0033_auto_20180622_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiondetails',
            name='igst_amount',
            field=models.FloatField(blank=True, db_column='IGSTAMT', null=True),
        ),
    ]
