# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0035_auto_20180622_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondetails',
            name='invoice_no',
            field=models.CharField(db_column='INVNO', default=1, max_length=15),
            preserve_default=False,
        ),
    ]
